/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#444748",
        "outline": "#747878",
        "surface-container-low": "#f4f4f2",
        "surface-container-high": "#e8e8e6",
        "on-background": "#1a1c1b",
        "surface-dim": "#dadad8",
        "primary": "#171818",
        "inverse-on-surface": "#f1f1ef",
        "on-secondary": "#ffffff",
        "on-surface": "#1a1c1b",
        "primary-fixed-dim": "#c8c6c6",
        "background": "#f9f9f7",
        "error": "#ba1a1a",
        "surface-tint": "#5f5e5e",
        "on-primary-fixed": "#1b1c1c",
        "tertiary-container": "#2b2d1d",
        "error-container": "#ffdad6",
        "on-secondary-container": "#745c00",
        "on-secondary-fixed-variant": "#574500",
        "secondary-fixed": "#ffe088",
        "on-tertiary-fixed-variant": "#474836",
        "tertiary-fixed-dim": "#c8c8b0",
        "outline-variant": "#c4c7c7",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "secondary-fixed-dim": "#e9c349",
        "surface-container": "#eeeeec",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#e4e4cc",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#241a00",
        "surface-variant": "#e2e3e1",
        "on-tertiary-container": "#94957f",
        "on-primary-container": "#949393",
        "surface": "#f9f9f7",
        "on-error": "#ffffff",
        "surface-bright": "#f9f9f7",
        "inverse-surface": "#2f3130",
        "secondary-container": "#fed65b",
        "secondary": "#735c00",
        "primary-container": "#2c2c2c",
        "on-tertiary-fixed": "#1b1d0e",
        "surface-container-highest": "#e2e3e1",
        "primary-fixed": "#e4e2e1",
        "tertiary": "#17190a",
        "on-primary-fixed-variant": "#474747",
        "inverse-primary": "#c8c6c6"
      },
      fontFamily: {
        "headline": ["Noto Serif", "serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
